### ISSUE TITLE
Error using --background option

### ISSUE THREAD

**Issue by devneal** [FabriceCastel/gvcci#10]
Running `python3 extract.py --background "#000000" ~/Pictures/Images/Wallpapers/08.jpg` yields
```
Traceback (most recent call last):
  File "extract.py", line 120, in <module>
    if (bg_color[2] < 0.5):
IndexError: index 2 is out of bounds for axis 0 with size 1
```
When I print `bg_color` at this point, I see `array([[ 0., 0., 0.]])`, so maybe it should be `if (bg_color[0][2] < 0.5):`?

**Comment by nan0s7** [comment]
Hey, I know what the actual issue is and it's _technically_ a bug. When you run the command, since a hex value is assumed if you start to input a number there is no need to tell the program it's actually a hex code. So you (currently) have to exclude the hash, and thus the following command works on my system:
`python3 extract.py --background "000000" ~/Pictures/blah.png`
Of course this should be checked for when dealing with the arguments but for now it's a work-around. :)

**Comment by FabriceCastel** [comment]
@devaneal you're right on the money about the indexing issue, `bg_color[0][2] < 0.5` is indeed what the code should look like. I've made the change to fix this problem :+1:

@nan0s7 not to bust your chops but that workaround won't do what you think it does 😛 

The custom background assignment is wrapped in `if config[background_color_param_name][0] == "#"` so if the param doesn't start with a `#` then the script doesn't try to parse it at all - so what would happen in that case is that it would automatically assign its best guess for a background without correcting it for saturation like it normally would.

That should resolve the issue, thanks for the heads up!
