### ISSUE TITLE
iTerm Dynamic profile command /usr/local/bin/fish breaks new windows

### ISSUE THREAD

**Issue by andreiciceu** [FabriceCastel/gvcci#15]
### Description
The created iTerm Dynamic profile tries to run a not existent script `/usr/local/bin/fish`, thus breaking the launch of a new temrinal window.
<img width="582" alt="image" src="https://user-images.githubusercontent.com/9255607/39351393-11f5f31c-4a0a-11e8-9f0d-ac46d9b85aac.png">

### Steps to Reproduce

1. Run ./iterm_lazy
2. Set gvcci as default profile
3. Cmd+N to open new terminal window

**Expected behavior:** Maybe no command to be called on dynamic profile

**Actual behavior:** Command gets called, pipe breaks, new terminal windows don't work

Great work so far, keep it up 😁

**Comment by FabriceCastel** [comment]
The issue was that the /usr/local/bin/fish on start command was hard-coded in the iTerm profile template. This never caused an issue for myself or the friends I've had test it since we all use the fish shell (whoops).

I've removed the command from the template, so now if you pull the latest master, delete the profile from your iTerm preferences, re-run iterm_lazy.sh and set that dynamic profile as your default again, opening new terminal windows should work as intended.

Please verify that this fix works for you so I can close the ticket and thanks for the words of encouragement 😄

**Comment by andreiciceu** [comment]
Seems to be work now.
Many thanks!
