### ISSUE TITLE
Set wallpaper for multiple desktops

### ISSUE THREAD

**Issue by andreiciceu** [FabriceCastel/gvcci#16]
Hello,

I've looked in the docs but I couldn't find a way to set the wallpaper for all my desktops in OSX. I think it would be a useful option.
Is it possible?

Many thanks,
Andrei

**Comment by FabriceCastel** [comment]
Hi Andrei, I've been looking for a way to do this. It works fine for all currently open desktops (ones that are active/visible on your monitors) but not of "background" desktops, or ones that are out of view.

If you want to try another approach, the code in charge of this is [in the gvcci-apply repo](https://github.com/FabriceCastel/gvcci-apply/blob/master/wallpaper/darwin.sh). I'll happy take a pull request or any suggestions you might have on this :)

In the meantime I'll close this issue since I have no plans to fix this in the short term. Feel free to re-open an issue in gvcci-apply if you find a solution!
