### ISSUE TITLE
Dependency installer

### ISSUE THREAD

**Issue by nan0s7** [FabriceCastel/gvcci#3]
Hey,

Love what you're doing here - I always wanted a more refined version of `wal` and to get the specific codes and stuff from the background image. 

When I ran `python3 setup.py install` it'd error out. There would be an issue installing each dependency except for the hasel one.

To fix this, I manually had to run the commands `pip3 install numpy`, and the same for `cython`, `scikit-image` and `scikit-learn`.

But after doing those manually the setup exited fine and was able to use the next command to extract the hex values from my chosen image.

More information about my computer; running Solus OS with the 4.13.8-28.current kernel and Python 3, version 3.5.4. If you need someone to help out or test things I'm happy to help any way I can. 

Again, thanks for the awesome tool!
~ nan0s7

**Comment by FabriceCastel** [comment]
To be honest, I'm pretty new to Python (and package/dependency management with it) so this is a bit of a crapshoot on my end. I can't say I expected this to work flawlessly out of the box. I've looked into it and there seems to be some weirdness around how scikit-image and numpy behave when in the same set of dependencies (at least with the way I tried doing it).

I made some changes to the readme instructions. Now, the two steps to get the dependencies set up are to run `pip3 install cython numpy scikit-learn scikit-image` and then `python3 setup.py install`.

cython might have already been installed on my system so that's probably an oversight on my part.

Let me know if those steps work around the issues you.

**Comment by nan0s7** [comment]
It looks like that worked fine.

I was also wondering, when I look at the hex codes printed in the terminal I don't see a value for the "foreground" colour. Is there plans on adding that to the code, or do you assume they use a white colour for the text.

Thanks for your help.

**Comment by FabriceCastel** [comment]
Ah good good, I'll close out this issue then.

The foreground colour is the next item on my TODO list, so you can expect it to show up soon. I haven't yet decided which method I'll use to pick it but either way, I'll have something done about that in the short term.
